name: tests.yml
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: game_test
        ports:
          - 50001:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -p 50001 -U postgres; do
            echo "Waiting for postgres..."
            sleep 2
          done

      - name: Run tests
        env:
          ConnectionStrings__Default: "Host=localhost;Username=postgres;Password=password;Database=game_test;Port=50001"
        run: dotnet test